services:
  - type: web
    name: aquasentinel
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: PORT
        value: 8000

      - key: LLM_PROVIDER
        value: fallback

      - key: SARVAM_API_KEY
        sync: false

      - key: SARVAM_MODEL_NAME
        value: sarvam-2b

      - key: DEFAULT_DEVICE_ID
        value: AQUA-01

      - key: WATER_BODY_NAME
        value: Simulated Reservoir 01

      - key: DATABASE_URL
        value: sqlite:///./aquasentinel.db